import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased `}
			>
				<nav className="w-1/2 mx-auto">
					<ul className="flex items-center justify-between w-full p-2">
						<li className="nav-li">
							<Link href="/">Главная</Link>
						</li>
						<li className="nav-li">
							<Link href="/compare">Сравнение</Link>
						</li>
						<li className="nav-li">
							<Link href="/brackets">Интервалы</Link>
						</li>
					</ul>
				</nav>
				<div className="min-h-screen bg-neutral-50 text-black p-6">
					<div className="mx-auto max-w-6xl space-y-6">
						{children}
						<footer className="text-xs text-neutral-500">
							<p>
								Подсказка: для <span className="font-mono">cos(x)-x</span>' '
								хорошо работает Ньютона с x₀=1; для фиксированной точки
								используйте g(x)=cos(x) и relax=1.
							</p>
							<p className="mt-1">
								Поддерживаемые функции парсера на бэкенде:' '
								<span className="font-mono">
									ln, lg, exp, sqrt, sin, cos, tan
								</span>
								; константы: <span className="font-mono">e, pi</span>;
								операции:' '<span className="font-mono">+ - * / ^</span>.
							</p>
						</footer>
					</div>
				</div>
			</body>
		</html>
	)
}
